### ISSUE TITLE
class changes when using [

### ISSUE THREAD

**Issue by jakob-r** [mlr-org/mlrng#2]
IMHO it is strange and untypical that the subsetting operator changes the class of an object
```r
>Tasks$get("iris") -> iris
> class(iris)
[1] "ClassifTask"    "SupervisedTask" "Task"           "R6"            
> class(iris[])
[1] "data.table" "data.frame"
```

**Comment by berndbischl** [comment]
yup. this should produce a task

**Comment by berndbischl** [comment]
actually i dont know what it should produce...
what i do know is:
a) we need to define the API now, cleanly
b) we should not overwrite operators / have 2nd alternative ways to access stuff, until the basic ops are cleanly defined

**Comment by mllg** [comment]
All sugar has been removed.
